# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    # session: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true

    # pour lien https dans l'email de confirmation de cr√©ation d'un utilisateur
    router:
        default_uri: '%env(resolve:CLIENT_URL)%'
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers:
        - x-forwarded-for
        - x-forwarded-host
        - x-forwarded-proto
        - x-forwarded-port
        - x-forwarded-prefix

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

