lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(resolve:JWT_PASSPHRASE)%'
    token_ttl: 300 # in seconds, default is 3600
    token_extractors:
        cookie:
            enabled: true
            name:    BEARER
    set_cookies:
        BEARER: ~
    blocklist_token:
        enabled: true
        cache: cache.app